/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_connexion (void);
GtkWidget* create_inscription (void);
GtkWidget* create_mot_de_passe_oublie (void);
GtkWidget* create_Mes_informations_ (void);
GtkWidget* create_accueil (void);
GtkWidget* create_gestion_des_elections_ (void);
GtkWidget* create_ajout_election_ (void);
GtkWidget* create_modif_election_ (void);
GtkWidget* create_supprimer_election_ (void);
GtkWidget* create_gestion_utilisateur (void);
GtkWidget* create_ajout_utilisateur (void);
GtkWidget* create_modification_utlisateur (void);
GtkWidget* create_supprimer_utilisateur (void);
GtkWidget* create_Gestion_observateur_ (void);
GtkWidget* create_ajouter_observateur_ (void);
GtkWidget* create_modifier_observateur_ (void);
GtkWidget* create_supprimer_observateur_ (void);
GtkWidget* create_Gestion_electeur_ (void);
GtkWidget* create_Ajout__electeur (void);
GtkWidget* create_modifier___electeur (void);
GtkWidget* create_supprimer_electeur_ (void);
GtkWidget* create_gestion_des_listes_electorales_ (void);
GtkWidget* create_Ajout__liste_electorale_ (void);
GtkWidget* create_modifier___liste_electorale_ (void);
GtkWidget* create_supprimer_liste_electorale_ (void);
GtkWidget* create_Gestion_bureau_de_vote (void);
GtkWidget* create_ajouter_bureau_de_vote_ (void);
GtkWidget* create_modifier__bureau_de_vote_ (void);
GtkWidget* create_supprimer_bureau_de_vote_ (void);
GtkWidget* create_Gestion_agent_de_bureau_de_vote (void);
GtkWidget* create_ajouter_agent_de_bureau_de_vote_ (void);
GtkWidget* create_modifier_agent_de_bureau_de_vote_ (void);
GtkWidget* create_supprimer_agent_de_bureau_de_vote_ (void);
GtkWidget* create_gestion__reclamation_ (void);
GtkWidget* create_ajout_reclamation_ (void);
GtkWidget* create_modif_reclamation_ (void);
GtkWidget* create_supprimer_reclamation_ (void);
